[package]
name = "RustyBoot"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10.0"
uefi = "0.35.0"
uefi-services = "0.26.0"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[[bin]]
name = "RustyBoot"
test = false
bench = false
