<<<<<<< HEAD
=======
# === Cargo.toml ===
>>>>>>> 4261a8a (A bootloader in Rust with capabilities to boot into ext partitions)
[package]
name = "RustyBoot"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
<<<<<<< HEAD
=======
lto = true
codegen-units = 1

[[bin]]
name = "RustyBoot"
test = false
bench = false
>>>>>>> 4261a8a (A bootloader in Rust with capabilities to boot into ext partitions)
