[build]
target = "i686-bootloader.json"

[target.i686-bootloader]
linker = "ld.lld"
rustflags = [
    "-C",
    "link-arg=-Tlinker.ld",
    "-C",
    "relocation-model=static",
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-static",
    "-C",
    "link-arg=elf_i386",
    "-C",
    "link-arg=--build-id=none",
    "-C",
    "panic=abort",
]
