[build]
target = "i686-bootloader.json"

[unstable]
build-std = ["core", "compiler_builtins"]

[target.i686-bootloader]
linker = "ld.lld"
rustflags = [
    "-Cpanic=abort",
    "-Crelocation-model=static",
    "-Clink-arg=-Tlinker.ld",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
    "-Clink-arg=--build-id=none",
]
