name: RustyBoot CI

# Trigger on any push or pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Rust dependencies for faster builds
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Set up Rust
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      # Build the project
      - name: Build RustyBoot
        run: cargo build --all

      # Run tests
      - name: Run tests
        run: cargo test --all
