name: RustyBoot CI
# Trigger on any push or pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
      # Cache Rust dependencies for faster builds
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Set up Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      # Build the project
      - name: Build RustyBoot
        run: cargo build --all
      # Run tests
      - name: Run tests
        run: cargo test --all
